version: '3.8'
services:
  app:
    container_name: UnpaidOrdersAPP
    build:
      context: .
    restart: always
    ports:
      - '3005:3005'
  UnpaidOrdersDB:
    container_name: UnpaidOrdersDB
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5434:5432'
    volumes: 
      - ./db:/var/lib/postgresql/data
volumes:
  db:
    driver: local